### ISSUE TITLE
Caching

### ISSUE THREAD

**Issue by subdesign** [AlexRadch/Laravel-LdapCredentials#1]
Hey Alex, 

Do you have any idea what if the LDAP server isn't running, how to authenticate the users? Maybe implementing some caching could solve the problem?
Have you ever think about that?

Thanks

**Comment by AlexRadch** [comment]
I don't think about it.
Laravel have user remembering functionality. See http://laravel.com/docs/5.1/authentication#remembering-users documentation. Your users table must include the string remember_token column, which will be used to store the "remember me" token. And add remember me checkbox in login form.

**Comment by subdesign** [comment]
Yeah, true. Thanks !
